<?php

/**
 * @file
 * Contains pmmi_twitter.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\StreamWrapper\StreamWrapperManager;
use Drupal\Core\Template\Attribute;
use Drupal\file\Entity\File;

/**
 * Implements hook_help().
 */
function video_provider_jwplayer_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the video_provider_jwplayer module.
    case 'help.page.video_provider_jwplayer':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('JW Player') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function video_provider_jwplayer_theme_suggestions_field_alter(&$suggestions, $variables) {
  /** @var \Drupal\node\Entity\Node $node */
  if (
    @$variables["element"]["#field_name"] !== ['field_showcase'] ||
    @$variables['element']['#field_type'] !== 'video' ||
    @$variables['element']['#formatter'] !== 'video_embed_player'
  ) {
    return;
  }
  $suggestions[] = 'field__jwshowcase';

  return $suggestions;
}

/**
 * Implements template_preprocess_html().
 */
function video_provider_jwplayer_preprocess_html(&$variables) {
  if (!getJwshowcaseNode()) {
    return $variables;
  }
  // HTML element attributes.
  $attributes = [];
  $attributes['ng-app'] = 'app';
  $attributes['ng-controller'] = 'RootController as rootVm';
  $variables['html_attributes'] = new Attribute($attributes);

  // Added JW Showcase classes to body.
  $variables['attributes']['class'][] = "jw-theme-{{ ::rootVm.config.theme }} jw-flag-loading-config jw-flag-no-focus";
  $variables['#attached']['library'][] = 'video_provider_jwplayer/jw-showcase.bridge';

  /**
   *   <script>
  window.configLocation = './config.json';
  </script>
   */
}

/**
 * Get the jwshowcase node from current route.
 *
 * @return \Drupal\node\Entity\Node|null
 */
function getJwshowcaseNode() {
  if ($node = \Drupal::routeMatch()->getParameter('node')) {
    $VideoFields = array_filter($node->getFieldDefinitions(), function ($field) {
      /** @var \Drupal\Core\Field\FieldDefinitionInterface $field */
      return $field->getType() == 'video';
    });
    foreach ($VideoFields as $field) {
      $fieldValue = $node->{$field->getName()}->getValue();
      $target_id = @$fieldValue[0]['target_id'];
      if (!$target_id) {
        continue;
      }
      $file = File::load($target_id);
      if (!$file) {
        continue;
      }
      $scheme = StreamWrapperManager::getScheme($file->getFileUri());
      if ($scheme === "jwshowcase") {
        return $node;
      }
    }
  }

  return NULL;
}
